/*

 @namespace getterjs
 @version 0.0.5
 @author kevin von flotow
 2014 - MIT license */
(function(g){function d(a){if(!(this instanceof d))return new d(a);this.length=0;if(Array.isArray(a))for(var b=0,c=a.length;b<c;++b)l.call(this,a[b]);else a&&l.call(this,a)}function l(a,b){if(a.appendChild)this[this.length++]=a;else{b=b||k;a=a.toString();for(var c=[],f=0,e;4>f;++f)if(e=n[f],!e.regex||e.regex.test(a)){c=e.fn(a,b);break}for(f=c.length;this.length<f;)this[this.length]=c[this.length++]}}var k=g.document,m=function(a,b){for(var c=0;6>c;++c)if(a[b])return b}(k.documentElement,"matches matchesSelector webkitMatchesSelector mozMatchesSelector msMatchesSelector oMatchesSelector".split(" ")),
n=[{regex:/^#[-A-Za-z0-9_][-A-Za-z0-9_:.]*$/,fn:function(a,b){var c=[],f=b===k?k.getElementById(a.substr(1)):b.querySelector(a);f&&c.push(f);return c}},{regex:/^\.[-A-Za-z0-9_:.]*$/,fn:function(a,b){return b.getElementsByClassName(a.substr(1))}},{regex:/^[A-Za-z][-A-Za-z0-9_:.]*$/,fn:function(a,b){return b.getElementsByTagName(a)}},{fn:function(a,b){return b.querySelectorAll(a)}}];d.prototype={each:function(a){for(var b=0;b<this.length;++b)a.call(this,this[b],b);return this},eq:function(a){return new d(this[a]?
this[a]:void 0)},exec:function(){var a=arguments;if(0!==a.length)for(var b=Array.prototype.shift.call(a).split(" "),c=b.length-1,f=0,e,d,h,g;f<this.length;++f){d=e=this[f];for(h=0;h<c&&"undefined"!==typeof e[b[h]];++h)e=d=e[b[h]];if((e=e[b[c]])&&(g=e.apply(d,a)))return g}},filter:function(a){for(var b=0,c=[];b<this.length;++b)this[b][m](a)&&c.push(this[b]);return new d(c)},find:function(a){for(var b=d(),c=0;c<this.length;++c)l.call(b,a);return b},first:function(){return this[0]?new d(this[0]):this},
is:function(a){return this[0]?this[0][m](a):!1},last:function(){return this[0]?new d(this[this.length-1]):this},remove:function(){for(var a=0,b;a<this.length;++a)b=this[a],b.remove?b.remove():b.parentNode&&b.parentNode.removeChild&&b.parentNode.removeChild(b);this.length=0},set:function(a,b){a=a.split(" ");for(var c=a.length-1,f=0,e,d;f<this.length;++f){e=this[f];for(d=0;d<c&&"undefined"!==typeof e[a[d]];++d)e=e[a[d]];e[a[c]]=b}return this}};g.Getter=d;"undefined"===typeof g.$&&(g.$=d)})(window);
