/*
 getter v0.0.2
 2014 - kevin von flotow
 MIT license
*/
(function(f){function d(a){if("undefined"===typeof a)return console.log("Getter: selector is not defined");if(!(this instanceof d))return new d(a);this.length=0;if(Array.isArray(a))for(var b=0,c=a.length;b<c;++b)g.call(this,a[b]);else g.call(this,a.toString());k.call(this)}function g(a){if(a.appendChild)this[this.length++]=a;else{a=a.toString();for(var b=[],c=0,d;4>c;++c)if(d=l[c],!d.regex||d.regex.test(a)){b=d.fn(a);break}for(a=b.length;this.length<a;)this[this.length]=b[this.length++]}}function k(){var a=
this;Object.defineProperty(a,"classList",{value:{add:function(b){for(var c=0;c<a.length;++c)a[c].classList.add(b)},contains:function(b){return a[0]?a[0].classList.contains(b):!1},remove:function(b){for(var c=0;c<a.length;++c)a[c].classList.remove(b)},toggle:function(b){for(var c=0;c<a.length;++c)a[c].classList.toggle(b)}}})}var e=f.document,h=function(a){return a.matches?"matches":a.matchesSelector?"matchesSelector":a.webkitMatchesSelector?"webkitMatchesSelector":a.mozMatchesSelector?"mozMatchesSelector":
a.msMatchesSelector?"msMatchesSelector":a.oMatchesSelector?"oMatchesSelector":!1}(e.documentElement);d.logging=function(a){};var l=[{regex:/^#[-A-Za-z0-9_][-A-Za-z0-9_:.]*$/,fn:function(a){var b=[];(a=e.getElementById(a.substr(1)))&&b.push(a);return b}},{regex:/^\.[-A-Za-z0-9_:.]*$/,fn:function(a){return e.getElementsByClassName(a.substr(1))}},{regex:/^[A-Za-z][-A-Za-z0-9_:.]*$/,fn:function(a){return e.getElementsByTagName(a)}},{fn:function(a){return e.querySelectorAll(a)}}];d.prototype.each=function(a){for(var b=
0;b<this.length;++b)a.call(this,this[b],b);return this};d.prototype.eq=function(a){};d.prototype.exec=function(){var a=arguments;if(0!==a.length){var b=Array.prototype.shift.call(a);if(0!==this.length){if(!this[0][b])return console.log("getter: method does not exist");for(var c=0;c<this.length;++c)this[c][b].apply(this[c],a)}}};d.prototype.filter=function(a){for(var b=0,c=[];b<this.length;++b)this[b][h](a)&&c.push(this[b]);return new d(c)};d.prototype.first=function(){return this[0]?new d(this[0]):
this};d.prototype.is=function(a){return this[0]?this[0][h](a):!1};d.prototype.last=function(){return this[0]?new d(this[this.length-1]):this};d.prototype.remove=function(){for(var a=0,b;a<this.length;++a)b=this[a],b.remove?b.remove():b.parentNode&&b.parentNode.removeChild&&b.parentNode.removeChild(b);this.length=0};d.prototype.set=function(a,b){if(0!==this.length){if(!this[0].hasOwnProperty(a))return console.log("getter: property does not exist");for(var c=0;c<this.length;++c)this[c][a]=b;return this}};
f.Getter=d;"undefined"===typeof f.$&&(f.$=d)})(window);
